<feat> Созданы классы User, Item, Request, Booking, и их DTO классы U…
Solntmore/java-shareit pull request #1
Opened 2022-11-22 19:38 UTC by Solntmore

<feat> Созданы классы User, Item, Request, Booking, и их DTO классы UserDTO, ItemDTO, RequestDTO, BookingDTO
<feat> Созданы мапперы UserMapper и ItemMapper преобразующие объект в его DTO версию
<feat> Создан enum класс BookingStatus для указания возможных значений поля status класса Booking
<feat> Контроллер ItemController теперь поддерживает создание, обновление айтемов, поиск по владельцу или ключевым словам.
<feat> Контроллер UserController теперь поддерживает создание, обновление и удаление пользователя, а также поиск всех пользователей и с конкретным id.
<feat> Созданы специализированные Exception классы для обозначения кастомных ошибок
<feat> Теперь контроллеры возвращают Dto версии Item и User, скрывая лишние параметры объектов.
<feat> Удалены лишние импорты.

2022-11-23 22:00 UTC, Fleaman777 requested changes

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/Counter.java
> +public class Counter {
как говорится, это немного оверхэд, 
создавать для каунтера отдельный компонент, 

можно просто ограничется полем класса внутри репозитория, и методом, который будет инкрементить это поле, 

почему такой компонент немного оверинжиниринт, т.к. у каждого репозитория должен быть свой каунтер + в будущем, при использовании ДБ, айди будет инкрементится автоматически

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> findItemsWithParameters(@RequestHeader("X-Sharer-User-Id") long userId,
X-Sharer-User-Id - можно вынести в константу

относится ко всем похожим местам

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            return itemService.findItemByDescriptionAndOwnerId(query);
по хорошему, логики в контроллере не должно быть много, максимум отлов разных исключений и возврат нужного еррор кода, но для этого часто используют еррор хэндлинг 

условие которое тебя написано, можно было бы перенсти в слой сервиса

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +    private final HashMap<Long, Item> itemsMap = new HashMap<>();
лучше указать более широкий тип Map, 
так, если поменятся реализация itemsMap, например будет LinckedHashMap, код все равно будет работать

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +    private final Counter counter = new Counter();
поскольку Counter - Spring компонент, то можно заавтовайрить,
но на самом деле, этот компонент особо не нужен... (указал почему, в комменте в классе Counter)

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                .collect(Collectors.toList());
отличный стрим, все правильно построено

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/exceptions/ItemNotFoundException.java
> +@ResponseStatus(value = HttpStatus.NOT_FOUND)
хороший вариант с созданием эксепшена и назначением ему определенного статуса, так можно не создавать отдельный эксепшен хэндлер

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +    private final Counter counter = new Counter();
аналогичные комментарии с item стореджом

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +        }
большая вложенность ифов ухудшает восприятие кода, 
попробуй немного перестроить логику, можешь часть вынести в отдельные методы, как ты это сделал с patternMatches

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +    private boolean patternMatches(String emailAddress) {
неплохое названием. но довольно общее, 
надо что-то более конкретное, что бы быстрее улавливать смысл метода

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +        Optional<String> optionalEmail = Optional.ofNullable(updateUser.getEmail());
попробуй этот email тоже валидировать через аннотацию

если получится, код может получится и компактей, и гармоничней.
ничего страшного, если не получится, главное попытка)

2022-11-23 22:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +package ru.practicum.shareit.item;
видел, что в задании как-то неоднозначно написано про создание доп пекеджей, 

но мне кажется, можно уже сейчас, в жтом спрните, создать соответсвующие пекеджи внутри user и item: controller, service .... 

и уже спокойно в будущем их наполнять

2022-11-24 10:51 UTC, Solntmore commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> findItemsWithParameters(@RequestHeader("X-Sharer-User-Id") long userId,
По данному исправлению есть вопрос, задал в Slack

2022-11-26 20:28 UTC, merged