Add item requests
Solntmore/java-shareit pull request #3
Opened 2022-12-25 15:17 UTC by Solntmore

<feat> Добавлены классы Request, RequestRequestDto и ResponseRequestDto, RequestMapper
<feat> Создан RequestController, RequestService и RequestRepository
<feat> Добавлена пагинация для эндпойнтов GET /requests/all, GET /items, GET /items/search, GET /bookings и GET /bookings/owner.
<feat> Добавлены интеграционные тесты UserServiceTest и ItemServiceTest
<feat> Добавлены интеграционные тесты BookingServiseTest и RequestServiseTest
<feat> Добавлены интеграционные тесты для контроллера UserController(UserControllerMockMvcIntegrationTest)
<feat> Добавлены интеграционные тесты для контроллера ItemController(ItemControllerMockMvcIntegrationTest)
<feat> Добавлены интеграционные тесты для контроллера BookingController(BookingControllerMockMvcIntegrationTest)
<feat> Добавлены интеграционные тесты для контроллера RequestController(RequestControllerMockMvcIntegrationTest)
<feat> Добавлены тесты на сериализацию всех responseDto.

2022-12-26 15:11 UTC, Fleaman777 requested changes

2022-12-26 15:11 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +                true, 3);
общие requestItemDto... можно было бы вынести в метод с аннотацией @BeforeEach

2022-12-26 15:11 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/RequestControllerMockMvcIntegrationTest.java
> +    @Sql(statements = {RESET_IDS, CREATE_USERS, CREATE_ITEMS, CREATE_REQUESTS})
вроде как эту аннотацию можно переместить на уровень класса, что бы не дублировать над методами

2022-12-26 15:11 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/RequestControllerMockMvcIntegrationTest.java
> +                                .header("X-Sharer-User-Id", "3")
X-Sharer-User-Id - тоже можно было бы вынести в константу

2022-12-26 17:57 UTC, Solntmore commented on src/test/java/ru/practicum/shareit/request/RequestControllerMockMvcIntegrationTest.java
> +    @Sql(statements = {RESET_IDS, CREATE_USERS, CREATE_ITEMS, CREATE_REQUESTS})
Я в разных методах использую разную конфигурацию, где-то нужно предсозданные запросы, где-то нет, и так далее.

2022-12-28 14:31 UTC, Fleaman777 approved these changes

2023-01-07 11:03 UTC, merged